# Generated by Django 5.0.7 on 2024-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="ссылка на видео"
            ),
        ),
    ]
